src/Entity/Company.php
<?php

namespace App\Entity;

use App\Repository\CompanyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CompanyRepository::class)
 */
class Company
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone_number;

    /**
     * @ORM\Column(type="string", length=255)
     * @ORM\JoinColumn(nullable=false)
     */
    private $siret;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="companies")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Governance::class, inversedBy="companies")
     */
    private $governance;

    /**
     * @ORM\OneToOne(targetEntity=Account::class, inversedBy="company", cascade={"persist", "remove"})
     */
    private $account;

    /**
     * @ORM\Column(type="boolean")
     */
    private $validated;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="companies")
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity=Post::class, mappedBy="company")
     */
    private $posts;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $provider;

    public function __construct()
    {
        $this->companyUsers = new ArrayCollection();
        $this->user = new ArrayCollection();
        $this->posts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(string $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(string $siret): self
    {
        $this->siret = $siret;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(User $user): self
    {
        if (!$this->user->contains($user)) {
            $this->user[] = $user;
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->user->contains($user)) {
            $this->user->removeElement($user);
        }

        return $this;
    }

    public function getGovernance(): ?Governance
    {
        return $this->governance;
    }

    public function setGovernance(?Governance $governance): self
    {
        $this->governance = $governance;

        return $this;
    }

    public function getAccount(): ?Account
    {
        return $this->account;
    }

    public function setAccount(?Account $account): self
    {
        $this->account = $account;

        return $this;
    }

    public function getValidated(): ?bool
    {
        return $this->validated;
    }

    public function setValidated(bool $validated): self
    {
        $this->validated = $validated;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Post[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setCompany($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->contains($post)) {
            $this->posts->removeElement($post);
            // set the owning side to null (unless already changed)
            if ($post->getCompany() === $this) {
                $post->setCompany(null);
            }
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getProvider(): ?bool
    {
        return $this->provider;
    }

    public function setProvider(?bool $provider): self
    {
        $this->provider = $provider;

        return $this;
    }
    
}

src/Entity/Governance.php
<?php

namespace App\Entity;

use App\Repository\GovernanceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=GovernanceRepository::class)
 */
class Governance
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $money_name;

    /**
     * @ORM\OneToMany(targetEntity=GovernanceUserInformation::class, mappedBy="governance")
     */
    private $governanceUserInformation;

    /**
     * @ORM\OneToMany(targetEntity=Company::class, mappedBy="governance")
     */
    private $companies;

    /**
     * @ORM\OneToMany(targetEntity=Particular::class, mappedBy="governance")
     */
    private $particulars;

    /**
     * @ORM\OneToOne(targetEntity=Currency::class, mappedBy="governance", cascade={"persist", "remove"})
     */
    private $currency;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->governanceUserInformation = new ArrayCollection();
        $this->companies = new ArrayCollection();
        $this->particulars = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getMoneyName(): ?string
    {
        return $this->money_name;
    }

    public function setMoneyName(string $money_name): self
    {
        $this->money_name = $money_name;

        return $this;
    }

    /**
     * @return Collection|GovernanceUserInformation[]
     */
    public function getGovernanceUserInformation(): Collection
    {
        return $this->governanceUserInformation;
    }

    public function addGovernanceUserInformation(GovernanceUserInformation $governanceUserInformation): self
    {
        if (!$this->governanceUserInformation->contains($governanceUserInformation)) {
            $this->governanceUserInformation[] = $governanceUserInformation;
            $governanceUserInformation->setGovernance($this);
        }

        return $this;
    }

    public function removeGovernanceUserInformation(GovernanceUserInformation $governanceUserInformation): self
    {
        if ($this->governanceUserInformation->contains($governanceUserInformation)) {
            $this->governanceUserInformation->removeElement($governanceUserInformation);
            // set the owning side to null (unless already changed)
            if ($governanceUserInformation->getGovernance() === $this) {
                $governanceUserInformation->setGovernance(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Company[]
     */
    public function getCompanies(): Collection
    {
        return $this->companies;
    }

    public function addCompany(Company $company): self
    {
        if (!$this->companies->contains($company)) {
            $this->companies[] = $company;
            $company->setGovernance($this);
        }

        return $this;
    }

    public function removeCompany(Company $company): self
    {
        if ($this->companies->contains($company)) {
            $this->companies->removeElement($company);
            // set the owning side to null (unless already changed)
            if ($company->getGovernance() === $this) {
                $company->setGovernance(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Particular[]
     */
    public function getParticulars(): Collection
    {
        return $this->particulars;
    }

    public function addParticular(Particular $particular): self
    {
        if (!$this->particulars->contains($particular)) {
            $this->particulars[] = $particular;
            $particular->setGovernance($this);
        }

        return $this;
    }

    public function removeParticular(Particular $particular): self
    {
        if ($this->particulars->contains($particular)) {
            $this->particulars->removeElement($particular);
            // set the owning side to null (unless already changed)
            if ($particular->getGovernance() === $this) {
                $particular->setGovernance(null);
            }
        }

        return $this;
    }

    public function getCurrency(): ?Currency
    {
        return $this->currency;
    }

    public function setCurrency(Currency $currency): self
    {
        $this->currency = $currency;

        // set the owning side of the relation if necessary
        if ($currency->getGovernance() !== $this) {
            $currency->setGovernance($this);
        }

        return $this;
    }
}

src/Form/GovernanceType.php
<?php

namespace App\Form;

use App\Entity\Governance;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GovernanceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('money_name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Governance::class,
        ]);
    }
}

src/Controller/API/GovernanceController.php
<?php

namespace App\Controller\API;

use App\Repository\GovernanceRepository;
use Symfony\Component\Routing\Annotation\Route;
use App\Controller\API\ApiController;
use Swagger\Annotations as SWG;

class GovernanceController extends ApiController
{
    /**
     * @Route("/api/governances", name="api_governances", methods="GET")
     *
     * @SWG\Response(
     *     response=200,
     *     description="Governances listed"
     * )
     * @SWG\Tag(name="governances")
     *
     * @param GovernanceRepository $governanceRepository
     *
     * @return Response
     */
    public function getAllGovernances(GovernanceRepository $governanceRepository)
    {
        $governances = $governanceRepository->findAll();

        $governanceArray = [];
    
        foreach ($governances as $governance) {
            $governanceArray[] = [
                'id' => $governance->getId(),
                'governance_name' => $governance->getName()
            ];
        }

        return $this->responseOk($governanceArray);
    }
}

src/Controller/Admin/GovernanceController.php
<?php

namespace App\Controller\Admin;

use App\Repository\GovernanceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class GovernanceController extends AbstractController
{
    /**
     * @Route("/admin/governance", name="admin_governance")
     *
     * @IsGranted("ROLE_SUPER_ADMIN")
     */
    public function index(GovernanceRepository $repository)
    {
        $governances = $repository->findAll();

        return $this->render('admin/governance/list.html.twig', compact('governances'));
    }
}

src/Controller/SuperAdmin/GovernanceController.php
<?php

namespace App\Controller\SuperAdmin;

use App\Entity\Governance;
use App\Form\GovernanceType;
use App\Repository\GovernanceRepository;
use App\Repository\GovernanceUserInformationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/superadmin/governance", name="superadmin_governance_")
 *
 * @IsGranted("ROLE_SUPER_ADMIN")
 */
class GovernanceController extends AbstractController
{
    /**
     * @Route("/create", name="create", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $governance = new Governance();
        $form = $this->createForm(GovernanceType::class, $governance);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($governance);
            $entityManager->flush();
            $this->addFlash('success', 'La gouvernance a bien été créée');

            return $this->redirectToRoute('superadmin_home');
        }

        return $this->render('superAdmin/governance/create.html.twig', [
            'governance' => $governance,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="show", methods={"GET"})
     */
    public function show(Governance $governance, GovernanceUserInformationRepository $govUserInfoRepository): Response
    {
        $govUsersInformation = $govUserInfoRepository->findUserInformationByGovernanceId($governance->getId());

        return $this->render('superAdmin/governance/show.html.twig', [
            'govUsersInformation' => $govUsersInformation,
            'governance' => $governance
        ]);
    }

    /**
     * @Route("/{id}/edit", name="edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Governance $governance): Response
    {
        $form = $this->createForm(GovernanceType::class, $governance);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('superadmin_governance_show', ['id' => $governance->getId()]);
        }

        return $this->render('superAdmin/governance/edit.html.twig', [
            'governance' => $governance,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Display list of Governances.
     *
     * @Route("/", name="index")
     *
     * @param [type] $governanceRepository
     *
     * @return Response
     */
    public function index(GovernanceRepository $governanceRepository)
    {
        return $this->render('superAdmin/home.html.twig', [
            'governances' => $governanceRepository->findAll()
        ]);
    }
}

src/Controller/SuperAdmin/SuperAdminController.php
<?php

namespace App\Controller\SuperAdmin;

use App\Repository\GovernanceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class SuperAdminController extends AbstractController
{
    /**
     * @Route("/superadmin/home", name="superadmin_home")
     *
     * @IsGranted("ROLE_SUPER_ADMIN")
     */
    public function home(GovernanceController $governanceController, GovernanceRepository $governanceRepository )
    {
        return $this->render('superAdmin/home.html.twig', [
            'governances' => $governanceRepository->findAll()
        ]);
    }

    
}

templates/superAdmin/governance/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn-create btn-neymo">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/superAdmin/governance/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Governance{% endblock %}

{% block content %}
<div class="content-container">
    <div class="container-fluid" style="padding-right:60px;padding-left:60px">
        <div class="jumbotron">
            <a href="{{ path('superadmin_home') }}">Gouvernances</a>
    <h1>Créer une gouvernance</h1>

    {{ include('superAdmin/governance/_form.html.twig') }}
    </div>
    </div>
    </div>

{% endblock %}

templates/superAdmin/governance/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification de la gouvernance{% endblock %}

{% block content %}
     <div class="content-container text">
        <div class="container-fluid" style="padding-right:60px;padding-left:60px">
            <div class="jumbotron">
                <a href="{{ path('superadmin_governance_show', {'id': governance.id}) }}">Revenir à la Gouvernance</a>

    <h1>Modifier la Gouvernance {{ governance.name }}</h1>

    {{ include('superAdmin/governance/_form.html.twig', {'button_label': 'Modifier'}) }}

        </div>
    </div>
{% endblock %}

templates/superAdmin/governance/index.html.twig
<div class="d-flex flex-row justify-content-between align-items-center">
    <h2>Liste des gouvernances</h2>
    <a href="{{ path('superadmin_governance_create') }}" class="btn-create btn-neymo">Créer une gouvernance</a>
</div>
    <table class="table table-striped neymo-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nom de la gouvernance</th>
                <th>Nom de la monnaie</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for governance in governances %}
                <tr>
                    <td class="td-id">{{ governance.id }}</td>
                    <td>{{ governance.name }}</td>
                    <td>{{ governance.moneyName }}</td>
                    <td>
                        <a href="{{ path('superadmin_governance_show', {'id': governance.id}) }}">
                            <i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="Détails"></i>
                        </a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4">no records found</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

templates/superAdmin/governance/list.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    {% for governance in governances %}
        <li>{{ governance.name }}</li>
    {% endfor %}
{% endblock %}

templates/superAdmin/governance/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Governance{% endblock %}

{% block content %}
<div class="content-container">
        <div class="container-fluid">
            <div class="jumbotron">
                <a href="{{ path('superadmin_home') }}">Retour sur les Gouvernances</a><div>
                <h2>Information sur la gouvernance de {{ governance.name }}</h2>
                <table class="table table-striped neymo-table">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nom de la gouvernance</th>
                        <th>Nom de la monnaie</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="td-id">{{ governance.id }}</td>
                            <td>{{ governance.name }}</td>
                            <td>{{ governance.moneyName }}</td>
                            <td>
                                <a href="{{ path('superadmin_governance_edit', {'id' : governance.id}) }}" class="">
                                    <img src="{{ asset('/build/edit.svg') }}" alt="">
                                </a>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div class="d-flex flex-row justify-content-between align-items-center">
                    <h2>Administrateurs associés à cette gouvernance</h2>
                    <a href="{{ path('superadmin_admin_create', {'id': governance.id}) }}" class="btn-neymo btn-create">Ajouter un Administrateur</a>
                </div>
        <table class="table table-striped neymo-table">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Email</th>
                    <th scope="col">Prénom</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Rôle</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
        {% for user in govUsersInformation %}
        {% set admin = user %}
                <tr>
                    <td class="td-id">{{ user.user.id }}</td>
                    <td>{{ user.user.email }}</td>
                    <td>{{ user.firstName }}</td>
                    <td>{{ user.lastName }}</td>
                    <td>{{ user.role }}</td>
                    <td>
                        <div class="d-flex flex-row justify-content-end">
                            <a href="{{ path('superadmin_admin_edit', {'id' : user.id}) }}" class="">
                                <img src="{{ asset('/build/edit.svg') }}" alt="">
                            </a>
                            {{ include('superAdmin/admin/_delete_form.html.twig') }}
                        </div>
                    </td>
            {% endfor %}
                </tr>
            </tbody>
        </table>
        </div>
    </div>
</div>
{% endblock %}